---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vllm-route
spec:
  port:
    targetPort: vllm
  to:
    kind: Service
    name: vllm-service
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: Edge
  wildcardPolicy: None
