---
apiVersion: v1
kind: Service
metadata:
  name: vllm-service
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  ports:
    - name: vllm
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: vllm-inference
