---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-amd-demo
spec:
  replicas: 1
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: vllm-inference
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: vllm-inference
      annotations:
        alpha.image.policy.openshift.io/resolve-names: "*"
    spec:
      containers:
        - name: vllm
          image: vllm:latest
          imagePullPolicy: Always
          command:
            - /entrypoint/entrypoint.sh
          args: []
          envFrom:
            - secretRef:
                name: vllm-env
            - configMapRef:
                name: vllm-env
          ports:
            - containerPort: 8000
              name: vllm
              protocol: TCP
          resources:
            limits:
              cpu: 8
              memory: 192Gi
              amd.com/gpu: 1
            requests:
              cpu: 4
              memory: 128Gi
              amd.com/gpu: 1
          startupProbe:
            failureThreshold: 90
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /v1/models
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /entrypoint
              name: entrypoint
              readOnly: true
            - mountPath: /dev/shm
              name: dev-shm
            - mountPath: /.cache
              name: cache
            - mountPath: /vllm-workspace
              name: modeldir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: vllm
      serviceAccountName: vllm
      terminationGracePeriodSeconds: 30
      volumes:
        - name: entrypoint
          configMap:
            defaultMode: 493
            name: vllm-entrypoint
        - name: dev-shm
          emptyDir:
            medium: Memory
            sizeLimit: 12Gi
        - name: cache
          emptyDir: {}
        - name: modeldir
          emptyDir: {}
