---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - configmap-entrypoint.yaml
  - configmap-env.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
